import type { ActorType, AggregateType } from './eventEnvelope'

export type DomainProjectionOwner =
  | 'discovery'
  | 'shariah_status'
  | 'purification'
  | 'accounting'
  | 'provider_status'
  | 'audit'
  | 'worker_status'

export type DomainEventContract = {
  event_type: DomainEventType
  aggregate_type: AggregateType
  actor_type: ActorType
  actor_types?: readonly ActorType[]
  projection_owner: DomainProjectionOwner
  payload_fields: readonly string[]
}

export type DomainProjectionContract = {
  projection_owner: DomainProjectionOwner
  package_owner: '@owlfolio/ledger' | '@owlfolio/providers'
  route_owner: string
}

export const domainEventTypes = [
  'discovery_candidate_discovered',
  'discovery_candidate_queued_for_quick_screen',
  'discovery_candidate_rejected',
  'discovery_candidate_promoted_to_research_case',
  'queued_for_deep_dive',
  'deep_dive_started',
  'specialist_finding_recorded',
  'deep_dive_synthesis_drafted',
  'deep_dive_completed',
  'holding_valuation_recorded',
  'scheduled_task_defined',
  'scheduled_task_run_started',
  'scheduled_task_run_completed',
  'scheduled_task_run_failed',
  'provider_run_started',
  'provider_run_completed',
  'provider_run_failed',
  'certification_report_recorded',
  'shariah_evaluation_recorded',
  'shariah_status_changed',
  'shariah_gate_decision_recorded',
  'purification_obligation_recorded',
  'purification_payment_recorded',
  'accounting_snapshot_recorded',
  'cash_deposited',
  'cash_withdrawn',
  'dividend_income_recorded',
  'fee_charged',
  'holding_realized_gain_loss_recorded',
  'research_run_requested',
  'research_run_claimed',
  'research_run_failed',
  'deep_dive_approval_pending',
  'deep_dive_run_requested',
] as const

export type DomainEventType = (typeof domainEventTypes)[number]

export const domainEventContracts: readonly DomainEventContract[] = [
  {
    event_type: 'discovery_candidate_discovered',
    aggregate_type: 'discovery_candidate',
    actor_type: 'provider',
    projection_owner: 'discovery',
    payload_fields: [
      'candidate_id',
      'ticker',
      'company_name',
      'market',
      'strategy_id',
      'strategy_version',
      'discovery_source',
      'source_ids',
      'discovered_at',
      'status',
      'dedupe_key',
    ],
  },
  {
    event_type: 'discovery_candidate_queued_for_quick_screen',
    aggregate_type: 'discovery_candidate',
    actor_type: 'system',
    projection_owner: 'discovery',
    payload_fields: ['candidate_id', 'queue_id', 'status'],
  },
  {
    event_type: 'discovery_candidate_rejected',
    aggregate_type: 'discovery_candidate',
    actor_type: 'user',
    projection_owner: 'discovery',
    payload_fields: ['candidate_id', 'reason', 'status'],
  },
  {
    event_type: 'discovery_candidate_promoted_to_research_case',
    aggregate_type: 'discovery_candidate',
    actor_type: 'user',
    projection_owner: 'discovery',
    payload_fields: ['candidate_id', 'research_case_id', 'research_case_event_id', 'status'],
  },
  {
    event_type: 'queued_for_deep_dive',
    aggregate_type: 'research_case',
    actor_type: 'system',
    projection_owner: 'discovery',
    payload_fields: ['research_case_id', 'queue_id', 'candidate_id', 'strategy_id', 'strategy_version', 'source_ids'],
  },
  {
    event_type: 'deep_dive_started',
    aggregate_type: 'research_case',
    actor_type: 'worker',
    projection_owner: 'discovery',
    payload_fields: ['research_case_id', 'deep_dive_id', 'candidate_id', 'strategy_id', 'strategy_version', 'specialist_lanes', 'source_ids'],
  },
  {
    event_type: 'specialist_finding_recorded',
    aggregate_type: 'research_case',
    actor_type: 'provider',
    projection_owner: 'discovery',
    payload_fields: [
      'research_case_id',
      'finding_id',
      'deep_dive_id',
      'candidate_id',
      'strategy_id',
      'strategy_version',
      'specialist_lane',
      'finding_summary',
      'source_ids',
      'confidence',
      'caveats',
      'provider_run_id',
    ],
  },
  {
    event_type: 'deep_dive_synthesis_drafted',
    aggregate_type: 'research_case',
    actor_type: 'system',
    projection_owner: 'discovery',
    payload_fields: [
      'research_case_id',
      'synthesis_id',
      'deep_dive_id',
      'candidate_id',
      'strategy_id',
      'strategy_version',
      'synthesis_summary',
      'specialist_finding_ids',
      'source_ids',
      'confidence',
      'caveats',
      'provider_run_id',
    ],
  },
  {
    event_type: 'deep_dive_completed',
    aggregate_type: 'research_case',
    actor_type: 'system',
    projection_owner: 'discovery',
    payload_fields: [
      'research_case_id',
      'completion_id',
      'deep_dive_id',
      'candidate_id',
      'synthesis_id',
      'strategy_id',
      'strategy_version',
      'source_ids',
      'confidence',
      'caveats',
      'provider_run_id',
    ],
  },
  {
    event_type: 'holding_valuation_recorded',
    aggregate_type: 'holding',
    actor_type: 'worker',
    actor_types: ['user', 'worker'],
    projection_owner: 'accounting',
    payload_fields: [
      'snapshot_id',
      'holding_id',
      'price_per_share',
      'shares',
      'market_value',
      'currency',
      'valued_at',
      'valuation_source',
      'price_checked_at',
      'confidence',
      'caveat',
      'missing_data',
      'valued_by_actor_type',
      'valued_by_actor_id',
    ],
  },
  {
    event_type: 'scheduled_task_defined',
    aggregate_type: 'scheduled_task',
    actor_type: 'user',
    projection_owner: 'worker_status',
    payload_fields: ['scheduled_task_id', 'task_kind', 'cadence', 'enabled'],
  },
  {
    event_type: 'scheduled_task_run_started',
    aggregate_type: 'scheduled_task',
    actor_type: 'worker',
    projection_owner: 'worker_status',
    payload_fields: ['scheduled_task_id', 'run_id', 'started_at'],
  },
  {
    event_type: 'scheduled_task_run_completed',
    aggregate_type: 'scheduled_task',
    actor_type: 'worker',
    projection_owner: 'worker_status',
    payload_fields: ['scheduled_task_id', 'run_id', 'completed_at', 'result_summary'],
  },
  {
    event_type: 'scheduled_task_run_failed',
    aggregate_type: 'scheduled_task',
    actor_type: 'worker',
    projection_owner: 'worker_status',
    payload_fields: ['scheduled_task_id', 'run_id', 'failed_at', 'error_summary'],
  },
  {
    event_type: 'provider_run_started',
    aggregate_type: 'provider_run',
    actor_type: 'worker',
    projection_owner: 'provider_status',
    payload_fields: ['provider_run_id', 'provider_id', 'model_id', 'task_kind', 'started_at'],
  },
  {
    event_type: 'provider_run_completed',
    aggregate_type: 'provider_run',
    actor_type: 'provider',
    projection_owner: 'provider_status',
    payload_fields: ['provider_run_id', 'provider_id', 'model_id', 'completed_at', 'finish_reason'],
  },
  {
    event_type: 'provider_run_failed',
    aggregate_type: 'provider_run',
    actor_type: 'provider',
    projection_owner: 'provider_status',
    payload_fields: ['provider_run_id', 'provider_id', 'model_id', 'failed_at', 'error_summary'],
  },
  {
    event_type: 'certification_report_recorded',
    aggregate_type: 'provider_run',
    actor_type: 'worker',
    projection_owner: 'provider_status',
    payload_fields: ['certification_report_id', 'provider_id', 'support_level', 'generated_at', 'cases'],
  },
  {
    event_type: 'shariah_evaluation_recorded',
    aggregate_type: 'holding',
    actor_type: 'provider',
    projection_owner: 'shariah_status',
    payload_fields: ['evaluation_id', 'holding_id', 'status', 'policy_basis', 'source_ids'],
  },
  {
    event_type: 'shariah_status_changed',
    aggregate_type: 'holding',
    actor_type: 'user',
    projection_owner: 'shariah_status',
    payload_fields: ['holding_id', 'previous_status', 'new_status', 'changed_reason'],
  },
  {
    event_type: 'shariah_gate_decision_recorded',
    aggregate_type: 'decision',
    actor_type: 'system',
    projection_owner: 'shariah_status',
    payload_fields: [
      'gate_decision_id',
      'target_transition',
      'target_id',
      'research_case_id',
      'status',
      'allowed',
      'reasons',
      'required_source_ids',
      'missing_evidence',
      'conditional_allowed',
    ],
  },
  {
    event_type: 'purification_obligation_recorded',
    aggregate_type: 'purification_entry',
    actor_type: 'worker',
    projection_owner: 'purification',
    payload_fields: ['obligation_id', 'holding_id', 'amount', 'currency', 'period_start', 'period_end'],
  },
  {
    event_type: 'purification_payment_recorded',
    aggregate_type: 'purification_entry',
    actor_type: 'user',
    projection_owner: 'purification',
    payload_fields: ['payment_id', 'obligation_id', 'amount', 'currency', 'paid_at', 'recipient'],
  },
  {
    event_type: 'accounting_snapshot_recorded',
    aggregate_type: 'accounting_snapshot',
    actor_type: 'worker',
    projection_owner: 'accounting',
    payload_fields: [
      'snapshot_id',
      'period_start',
      'period_end',
      'nav',
      'current_value',
      'unrealized_gain_loss',
      'realized_gain_loss',
      'cash_balance',
      'deposits',
      'withdrawals',
      'dividends',
      'fees',
      'net_cash_flow',
      'audit_event_ids',
      'source_ids',
      'missing_data_warnings',
      'currency',
    ],
  },
  {
    event_type: 'cash_deposited',
    aggregate_type: 'cash_account',
    actor_type: 'user',
    projection_owner: 'accounting',
    payload_fields: ['cash_account_id', 'amount', 'currency', 'deposited_at'],
  },
  {
    event_type: 'cash_withdrawn',
    aggregate_type: 'cash_account',
    actor_type: 'user',
    projection_owner: 'accounting',
    payload_fields: ['cash_account_id', 'amount', 'currency', 'withdrawn_at'],
  },
  {
    event_type: 'dividend_income_recorded',
    aggregate_type: 'cash_account',
    actor_type: 'user',
    projection_owner: 'accounting',
    payload_fields: ['dividend_id', 'holding_id', 'cash_account_id', 'amount', 'currency', 'received_at', 'taxable_status'],
  },
  {
    event_type: 'fee_charged',
    aggregate_type: 'cash_account',
    actor_type: 'user',
    projection_owner: 'accounting',
    payload_fields: ['fee_id', 'cash_account_id', 'amount', 'currency', 'charged_at', 'fee_type'],
  },
  {
    event_type: 'holding_realized_gain_loss_recorded',
    aggregate_type: 'holding',
    actor_type: 'user',
    projection_owner: 'accounting',
    payload_fields: ['realized_gain_loss_id', 'holding_id', 'amount', 'currency', 'realized_at'],
  },
  {
    event_type: 'research_run_requested',
    aggregate_type: 'research_case',
    actor_type: 'user',
    projection_owner: 'worker_status',
    payload_fields: ['research_case_id', 'ticker', 'company_id', 'strategy_id', 'model_id', 'requested_by', 'decision_id'],
  },
  {
    event_type: 'research_run_claimed',
    aggregate_type: 'research_case',
    actor_type: 'worker',
    projection_owner: 'worker_status',
    payload_fields: ['research_case_id', 'run_id', 'claimed_at', 'worker_id'],
  },
  {
    event_type: 'research_run_failed',
    aggregate_type: 'research_case',
    actor_type: 'worker',
    projection_owner: 'worker_status',
    payload_fields: ['research_case_id', 'run_id', 'failed_at', 'error_summary'],
  },
  {
    event_type: 'deep_dive_approval_pending',
    aggregate_type: 'research_case',
    actor_type: 'system',
    projection_owner: 'worker_status',
    payload_fields: [
      'research_case_id',
      'ticker',
      'company_id',
      'quick_screen_source_ids',
      'quick_screen_event_id',
      'decision_id',
      'source_ledger_path',
      'strategy_id',
      'model_id',
    ],
  },
  {
    event_type: 'deep_dive_run_requested',
    aggregate_type: 'research_case',
    actor_type: 'user',
    projection_owner: 'worker_status',
    payload_fields: [
      'research_case_id',
      'ticker',
      'requested_by',
    ],
  },
] as const

export const domainProjectionContracts: readonly DomainProjectionContract[] = [
  { projection_owner: 'discovery', package_owner: '@owlfolio/ledger', route_owner: '/research/discovery' },
  { projection_owner: 'shariah_status', package_owner: '@owlfolio/ledger', route_owner: '/shariah' },
  { projection_owner: 'purification', package_owner: '@owlfolio/ledger', route_owner: '/purification' },
  { projection_owner: 'accounting', package_owner: '@owlfolio/ledger', route_owner: '/accounting' },
  { projection_owner: 'provider_status', package_owner: '@owlfolio/providers', route_owner: '/providers' },
  { projection_owner: 'audit', package_owner: '@owlfolio/ledger', route_owner: '/audit' },
  { projection_owner: 'worker_status', package_owner: '@owlfolio/ledger', route_owner: '/worker' },
]
