"""Alert listing operations (read-only — alerts are generated by the daemon)."""

from __future__ import annotations

from typing import Any

from src.db.schema import get_db


def list_alerts(unread_only: bool = True, limit: int = 20) -> list[dict[str, Any]]:
    """List alerts, newest first. Default is unread only."""
    conn = get_db()
    try:
        if unread_only:
            rows = conn.execute(
                "SELECT * FROM alerts WHERE read = 0 ORDER BY id DESC LIMIT ?",
                (limit,),
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT * FROM alerts ORDER BY id DESC LIMIT ?", (limit,)
            ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


def mark_all_read() -> int:
    """Mark every unread alert as read. Returns the count marked."""
    conn = get_db()
    try:
        cur = conn.execute("UPDATE alerts SET read = 1 WHERE read = 0")
        conn.commit()
        return cur.rowcount
    finally:
        conn.close()
